# Основные цвета
foreground              #C4C7C5
background              #1E2124
selection_foreground    #FFFFFF
selection_background    #4B535A

# Курсор
cursor                  #C4C7C5
cursor_text_color       #1E2124

# Цвета URL и подсветки
url_color               #6C757D
active_border_color     #6C757D
inactive_border_color   #444444

# ANSI palette
color0  #1E2124
color8  #444444

color1  #6C757D
color9  #8A949C

color2  #7A847D
color10 #97A39B

color3  #8C8C8C
color11 #A6A6A6

color4  #5E6870
color12 #78838C

color5  #727A82
color13 #8D97A1

color6  #87919A
color14 #A2ADB7

color7  #C4C7C5
color15 #FFFFFF
