cat > ~/.config/hypr/hyprlock.conf << 'EOF'
# =============================================
# Minimalistic Hyprlock — под твою палитру DWL
# =============================================

general {
    hide_cursor = true
}

background {
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.75
    contrast = 1.1
}

input-field {
    size = 280, 50
    dots_center = true
    outer_color = rgb(6C757D)
    inner_color = rgb(1E2124)
    font_color = rgb(C4C7C5)
    placeholder_text = assword
    check_color = rgb(6C757D)
    fail_color = rgb(6C757D)
    fail_text_color = rgb(ffffff)
    fail_timeout = 1500
    position = 0, -120
}

label {
    monitor =
    text = $TIME
    color = rgb(C4C7C5)
    font_size = 82
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 80
    halign = center
    valign = center
}
