#!/bin/bash

wmenu_cmd="wmenu -p 'Select server: ' -l 4 -f 'Roboto Mono Medium 12' -N 1E2124 -M 4B535A -S 6C757D"

choice=$(samp-cli --list | sed '1d' | nl -w1 -s'. ' | eval $wmenu_cmd | cut -d'.' -f1)

echo $choice

printf "%s\n" "$choice" | "samp-cli"
